### ISSUE TITLE
Typo when asking for accesstoken

### ISSUE THREAD

**Issue by StillGreen-san** [StillGreen-san/SalienBot#2]
"Past token here:" instead of "Paste token here:"

**Comment by StillGreen-san** [comment]
Line 105
Maybe also change this to "Paste token **down** here:"

**Comment by zurda** [comment]
Happy to fix this one, if it's up for grabs

**Comment by StillGreen-san** [comment]
@hakabuk sure

**Comment by StillGreen-san** [comment]
thanks @hakabuk
