### ISSUE TITLE
Load all global vars from file

### ISSUE THREAD

**Issue by StillGreen-san** [StillGreen-san/SalienBot#3]
Load all global? variables like REP_CLAN, START_ZONE, RE_TRIES, etc from file

**Comment by StillGreen-san** [comment]
not important enough to delay release

**Comment by DisturbedII** [comment]
i'm on it, do you want one config file or many?

**Comment by StillGreen-san** [comment]
one for everything including the current one would be preferable

**Comment by StillGreen-san** [comment]
implemented in v0.3 and merged into master
